### ISSUE TITLE
ImgSource.Both modal text does not respect dark mode

### ISSUE THREAD

**Issue by JakeDriscoll** [kotlincodes/image_picker_gallery_camera#3]
When in dark mode the modal for selecting camera or gallery has a white background and white text.

![image](https://user-images.githubusercontent.com/14319962/81296467-f2db0200-903f-11ea-918a-c500d3c837ca.png)

**Comment by kotlincodes** [comment]
@JakeDriscoll Added an option to customize the text. Thanks for reporting the issue.
