### ISSUE TITLE
iOS 14 Crash and Feature Request

### ISSUE THREAD

**Issue by mogsten** [kotlincodes/image_picker_gallery_camera#7]
When selecting From Gallery on iOS 14. Sometimes it works, however most of the time it crashes.
We have set all of the necessary permissions so we know that's not an issue

Also, is there a way to add a cancel button or some way of getting out of the pickImage popup to choose Camera or Gallery? Because at the moment, we are finding it very hard to get out of the screen once we've tapped into it, which will then lead us to a crash

**Comment by thedavidpeto** [comment]
Same here, did u find any solution?

**Comment by kotlincodes** [comment]
> When selecting From Gallery on iOS 14. Sometimes it works, however most of the time it crashes.
> We have set all of the necessary permissions so we know that's not an issue
> 
> Also, is there a way to add a cancel button or some way of getting out of the pickImage popup to choose Camera or Gallery? Because at the moment, we are finding it very hard to get out of the screen once we've tapped into it, which will then lead us to a crash

Hi 

Added an option to enable the close button. You can check it on v0.2.2
